# Generated by Django 5.0.7 on 2024-07-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='products', to='Product.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.ManyToManyField(related_name='products', to='Product.gender'),
        ),
    ]
