# Generated by Django 5.0.7 on 2024-07-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(default='ZARA', max_length=100, unique=True, verbose_name='slug'),
        ),
    ]
