# Generated by Django 5.0.7 on 2024-07-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_alter_brand_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ManyToManyField(default=1, related_name='products', to='Product.brand'),
        ),
    ]
