# Generated by Django 5.0.7 on 2024-07-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ManyToManyField(default=1, null=True, related_name='products', to='Product.brand'),
        ),
    ]
