# Generated by Django 5.0.7 on 2024-07-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100)),
                ('site_address', models.CharField(max_length=100)),
                ('about_us', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('copyright', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='setting')),
            ],
        ),
    ]
