# Generated by Django 5.0.7 on 2024-07-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=300)),
                ('message', models.TextField()),
                ('full_name', models.CharField(max_length=300)),
                ('is_read', models.BooleanField(default=False)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('answer', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
