# Generated by Django 5.0.7 on 2024-07-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactUs', '0002_contact_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='slug',
            field=models.SlugField(max_length=300, unique=True),
        ),
    ]
