# Generated by Django 5.0.7 on 2024-07-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactUs', '0003_alter_contact_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='temp/')),
            ],
        ),
    ]
