# Generated by Django 5.0.7 on 2024-07-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactUs', '0004_sendclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendclass',
            name='image',
            field=models.ImageField(upload_to='temp'),
        ),
    ]
